### PR TITLE
Adding placeholder support

### PR DESCRIPTION
**Pull request by peshrawahmed**
Hi, 

Thank you for this nice package. I used in one of my projects and realized that there is a small gap between the time scroll reaches and the element renders and the screen remains blank.
 I used the component on multiple components on the same page. I wanted to prevent the next element from being rendered while the previous one is still rendering. So I created a slot for the `!rendered` state.

### CODE REVIEW

**Comment by dell-mic** [comment]
Hi peshrawahmed,

Thank you very much for you contribution!

I am not sure I understood you use case completely tbh. In case you want to prevent rendering of elements which will be pushed out of the viewport again due to other elements rendering you could also give the component a height which is roughly the same of the finally rendered element?

Nevertheless, in general I like the idea of having a placeholder slot as a new feature. However, I would prefer to keep the current behavior when no placeholder is given i.e. do not introduce breaking change in terms of behavior for current users. Alternatively we could also introduce a property like 'showPlaceholder'. 
What do you think?

**Comment by peshrawahmed** [comment]
Hi Michael, 

I found difficult to explain what was happening and why I needed a placeholder.  As It was a complex issue and My english may not be enough as I am not a native speaker :) But for now I am using my own fork on my project and it works as I expect.

I agree with you that giving height will solve the problem I had. But having a placeholder, skeleton(when using bootstrap-vue) or some loading image may be better than a blank space. Especially when there are more than one components rendering on scroll, which may lead to a very long blank page if the data inside the components are fetched async.

As for breaking change issue, I don't think what I have done will introduce any breaking changes for the current users. As the placeholder slot is optional and the rest will good for the people who are using the current version.

I am not sure `showPlaceholder` prop would do anything new. as `placeholder` slot is optional and will not render while no data is inside.(As I said I am not sure about this. I may be wrong)

Thank you for your reply and have a nice day :)

**Comment by dell-mic** [comment]
> As for breaking change issue, I don't think what I have done will introduce any breaking changes for the current users. As the placeholder slot is optional and the rest will good for the people who are using the current version.

Yeah, you are absolutely right, my bad I missed that you added the styled placeholder just in the dev example ... sorry!

**Comment by peshrawahmed** [comment]
No problem. Looking forward for your evaluation. :)

**Comment by dell-mic** [comment]
Just merged your changes manually as there was a conflict in the package lock file because I did some dependency changes in the meantime.

I am a bit in a hurry today, but will release a new version including your feature in the next days.

Thank you very much :)

**Comment by dell-mic** [comment]
Just published as new version: 1.1.0

Feel free to give it a try and again many thanks for you contribution :)

**Pull request closed without merging**
